<#
.SYNOPSIS
    Installation script for Windows Maintenance scheduled task.

.DESCRIPTION
    Creates a scheduled task to run Windows Maintenance automatically.
    Provides interactive configuration or accepts parameters for automated installation.

.PARAMETER TaskName
    Name for the scheduled task (default: "Windows Maintenance")

.PARAMETER Schedule
    Schedule type: Daily, Weekly, Monthly, AtStartup, OnIdle (default: Weekly)

.PARAMETER Time
    Time to run in 24-hour format (default: "02:00")

.PARAMETER DaysOfWeek
    Days for Weekly schedule (default: "Sunday")

.PARAMETER RunAsSystem
    Run as SYSTEM account instead of current user

.PARAMETER Interactive
    Show interactive prompts for configuration

.EXAMPLE
    .\Install-MaintenanceTask.ps1

.EXAMPLE
    .\Install-MaintenanceTask.ps1 -Schedule Daily -Time "03:00"

.EXAMPLE
    .\Install-MaintenanceTask.ps1 -Schedule Weekly -DaysOfWeek "Sunday,Wednesday" -RunAsSystem

.NOTES
    File Name      : Install-MaintenanceTask.ps1
    Author         : Miguel Velasco
    Prerequisite   : PowerShell 5.1+, Administrator privileges
    Version        : 1.0.0
    Last Updated   : October 2025
#>

#Requires -Version 5.1
#Requires -RunAsAdministrator

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$TaskName = "Windows Maintenance",

    [Parameter(Mandatory=$false)]
    [ValidateSet("Daily", "Weekly", "Monthly", "AtStartup", "OnIdle")]
    [string]$Schedule = "Weekly",

    [Parameter(Mandatory=$false)]
    [string]$Time = "02:00",

    [Parameter(Mandatory=$false)]
    [string]$DaysOfWeek = "Sunday",

    [Parameter(Mandatory=$false)]
    [switch]$RunAsSystem = $false,

    [Parameter(Mandatory=$false)]
    [switch]$Interactive = $false
)

# Determine script location
$ScriptRoot = Split-Path -Parent $PSScriptRoot
$ModulePath = Join-Path $ScriptRoot "WindowsMaintenance.psd1"

# Verify module exists
if (-not (Test-Path $ModulePath)) {
    Write-Host "ERROR: WindowsMaintenance module not found at: $ModulePath" -ForegroundColor Red
    exit 1
}

# Import required modules
try {
    Import-Module (Join-Path $ScriptRoot "Modules\TaskScheduler.psm1") -Force
    Import-Module (Join-Path $ScriptRoot "Modules\Common\Logging.psm1") -Force
}
catch {
    Write-Host "ERROR: Failed to import required modules: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Windows Maintenance Task Installer" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# Interactive mode
if ($Interactive) {
    Write-Host "Configure scheduled maintenance task interactively`n" -ForegroundColor Yellow

    # Task name
    $InputTaskName = Read-Host "Task name [Windows Maintenance]"
    if ($InputTaskName) { $TaskName = $InputTaskName }

    # Schedule type
    Write-Host "`nSchedule types:"
    Write-Host "  1. Daily"
    Write-Host "  2. Weekly (recommended)"
    Write-Host "  3. Monthly"
    Write-Host "  4. At Startup"
    Write-Host "  5. On Idle"

    $ScheduleChoice = Read-Host "`nSelect schedule type [2]"
    $Schedule = switch ($ScheduleChoice) {
        "1" { "Daily" }
        "2" { "Weekly" }
        "3" { "Monthly" }
        "4" { "AtStartup" }
        "5" { "OnIdle" }
        default { "Weekly" }
    }

    # Time (for scheduled types)
    if ($Schedule -in @("Daily", "Weekly", "Monthly")) {
        $InputTime = Read-Host "Run time in 24-hour format [02:00]"
        if ($InputTime) { $Time = $InputTime }
    }

    # Days of week (for Weekly)
    if ($Schedule -eq "Weekly") {
        Write-Host "`nDays of week (comma-separated):"
        Write-Host "  Examples: Sunday  |  Monday,Wednesday,Friday  |  Saturday,Sunday"
        $InputDays = Read-Host "Days [Sunday]"
        if ($InputDays) { $DaysOfWeek = $InputDays }
    }

    # Run as SYSTEM
    $InputSystem = Read-Host "`nRun as SYSTEM account? [N]"
    $RunAsSystem = ($InputSystem -eq 'Y' -or $InputSystem -eq 'y')

    Write-Host ""
}

# Display configuration
Write-Host "Task Configuration:" -ForegroundColor Green
Write-Host "  Name:     $TaskName"
Write-Host "  Schedule: $Schedule"
if ($Schedule -in @("Daily", "Weekly", "Monthly")) {
    Write-Host "  Time:     $Time"
}
if ($Schedule -eq "Weekly") {
    Write-Host "  Days:     $DaysOfWeek"
}
Write-Host "  Run As:   $(if ($RunAsSystem) { 'SYSTEM' } else { $env:USERNAME })"
Write-Host "  Module:   $ModulePath`n"

# Confirm
if (-not $Interactive) {
    $Confirm = Read-Host "Create this scheduled task? [Y/N]"
    if ($Confirm -ne 'Y' -and $Confirm -ne 'y') {
        Write-Host "Installation cancelled." -ForegroundColor Yellow
        exit 0
    }
}

# Create wrapper script
$WrapperScriptPath = Join-Path $ScriptRoot "Scripts\Run-Maintenance.ps1"
$WrapperContent = @"
#Requires -Version 5.1
#Requires -RunAsAdministrator

# Windows Maintenance Wrapper Script
# Auto-generated by Install-MaintenanceTask.ps1

`$ModulePath = Join-Path `$PSScriptRoot "..\WindowsMaintenance.psd1"

try {
    Import-Module `$ModulePath -Force
    Invoke-WindowsMaintenance
}
catch {
    Write-Error "Maintenance failed: `$(`$_.Exception.Message)"
    exit 1
}
"@

try {
    # Create wrapper script
    $WrapperContent | Out-File -FilePath $WrapperScriptPath -Encoding UTF8 -Force
    Write-Host "Created wrapper script: $WrapperScriptPath" -ForegroundColor Green

    # Create scheduled task
    $TaskParams = @{
        TaskName = $TaskName
        ScriptPath = $WrapperScriptPath
        Schedule = $Schedule
        Description = "Automated Windows Maintenance - Created $(Get-Date -Format 'yyyy-MM-dd')"
    }

    if ($Schedule -in @("Daily", "Weekly", "Monthly")) {
        $TaskParams.Add("Time", $Time)
    }

    if ($Schedule -eq "Weekly") {
        $TaskParams.Add("DaysOfWeek", $DaysOfWeek)
    }

    if ($RunAsSystem) {
        $TaskParams.Add("RunAsSystem", $true)
    }

    $Success = New-MaintenanceTask @TaskParams

    if ($Success) {
        Write-Host "`n========================================" -ForegroundColor Green
        Write-Host "  Installation Successful!" -ForegroundColor Green
        Write-Host "========================================`n" -ForegroundColor Green

        Write-Host "Scheduled task created successfully." -ForegroundColor Green
        Write-Host "`nTo manage the task:" -ForegroundColor Cyan
        Write-Host "  - View in Task Scheduler: taskschd.msc"
        Write-Host "  - Run manually: Start-ScheduledTask -TaskName '$TaskName'"
        Write-Host "  - Disable: Disable-ScheduledTask -TaskName '$TaskName'"
        Write-Host "  - Remove: Unregister-ScheduledTask -TaskName '$TaskName'`n"
    }
    else {
        Write-Host "`nERROR: Failed to create scheduled task." -ForegroundColor Red
        exit 1
    }
}
catch {
    Write-Host "`nERROR: Installation failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
